nithin_dbt_proj:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: 
      http_path: 
      schema: default
      threads: 1
      token: 
      type: databricks
    prod:
      catalog: dbt_tutorial_prod
      host: 
      http_path: 
      schema: default
      threads: 1
      token: 
      type: databricks
  target: dev
